export const importedReports = [
  {
    name: "Hannah Arias",
    grade: "7",
    test: {
      id: "import-hannah-arias-2026-05-03",
      date: "2026-05-04T04:41:00.000Z",
      type: "Placement Test",
      score: 79,
      placement: "Pre-Algebra",
      currentReadiness: "On grade level",
      courseRecommendation: "Pre-Algebra",
      nextRecommendedTest: "A grade-level readiness diagnostic",
      missedTopics: ["Data Interpretation", "Exponents", "SAT Math Reasoning", "Fractions"],
      graphingPerformance: { correct: 1, total: 2, percent: 50 },
      satPerformance: { correct: 2, total: 5, percent: 40 },
      testDifficultyFit: "Appropriate",
      masteredLevel: false,
      challengeUnlocked: false,
      nextLevelGrade: "8",
      dailyPlan: [
        { day: 1, tasks: ["5 Data Interpretation questions", "3 Exponents questions"] },
        { day: 2, tasks: ["4 SAT Math Reasoning problems", "4 mixed grade-level questions"] },
      ],
      topicResults: [
        { topic: "Arithmetic", correct: 2, total: 2, percent: 100, difficulty: "Hard" },
        { topic: "Fractions", correct: 2, total: 3, percent: 67, difficulty: "Medium" },
        { topic: "Decimals", correct: 2, total: 2, percent: 100, difficulty: "Hard" },
        { topic: "Percents", correct: 2, total: 2, percent: 100, difficulty: "Hard" },
        { topic: "Negative Numbers", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Ratios and Proportions", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Basic Algebra", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Solving Equations", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Exponents", correct: 1, total: 2, percent: 50, difficulty: "Easy" },
        { topic: "Square Roots", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Word Problems", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Geometry Basics", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Graphing Basics", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "SAT Math Reasoning", correct: 2, total: 4, percent: 50, difficulty: "Easy" },
        { topic: "Data Interpretation", correct: 0, total: 1, percent: 0, difficulty: "Easy" },
      ],
    },
  },
  {
    name: "Liam DeVries",
    grade: "8",
    test: {
      id: "import-liam-devries-2026-05-01",
      date: "2026-05-01T20:22:00.000Z",
      score: 90,
      placement: "Above grade level",
      currentReadiness: "Algebra 1 ready",
      courseRecommendation: "Ready for Algebra 1 / Integrated Math 1, with above-grade challenge practice",
      nextRecommendedTest: "Grade 8 readiness review",
      missedTopics: ["Linear vs Nonlinear Relationships", "Systems of Equations", "Factoring"],
      graphingPerformance: { correct: 13, total: 14, percent: 93 },
      satPerformance: { correct: 6, total: 6, percent: 100 },
      topicResults: [
        { topic: "Graphing: Match Equation", correct: 2, total: 2, percent: 100, difficulty: "Hard" },
        { topic: "Graphing: Slope From Points", correct: 2, total: 2, percent: 100, difficulty: "Hard" },
        { topic: "Graphing: Y-Intercept", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Graphing: Word Problem Graph", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Linear vs Nonlinear Relationships", correct: 0, total: 1, percent: 0, difficulty: "Easy" },
        { topic: "Linear Equations and Inequalities", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Systems of Equations", correct: 0, total: 1, percent: 0, difficulty: "Easy" },
        { topic: "Linear Functions and Graphing", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Function Notation", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Exponents and Radicals", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Scientific Notation", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Square and Cube Roots", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Pythagorean Theorem", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Irrational Numbers", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Transformations", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Volume of 3D Shapes", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Scatter Plots and Best Fit", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Algebra 1 Readiness Word Problems", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Factoring", correct: 1, total: 2, percent: 50, difficulty: "Easy" },
        { topic: "Solving Quadratic Equations", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Graphing Parabolas", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "SAT Math Reasoning", correct: 2, total: 2, percent: 100, difficulty: "Hard" },
        { topic: "Data Interpretation", correct: 4, total: 4, percent: 100, difficulty: "Hard" },
      ],
    },
  },
  {
    name: "Leilani DeVries",
    grade: "10",
    test: {
      id: "import-leilani-devries-2026-05-01",
      date: "2026-05-01T19:08:00.000Z",
      score: 83,
      placement: "Algebra 2 ready",
      currentReadiness: "On grade level",
      courseRecommendation: "Ready for Integrated Math 3 / Algebra 2 with targeted review",
      nextRecommendedTest: "Integrated Math 2 readiness",
      missedTopics: ["Data Interpretation", "Trigonometry Basics", "SAT Math Reasoning"],
      graphingPerformance: { correct: 7, total: 9, percent: 78 },
      satPerformance: { correct: 1, total: 5, percent: 20 },
      topicResults: [
        { topic: "Fractions", correct: 5, total: 5, percent: 100, difficulty: "Hard" },
        { topic: "Negative Numbers", correct: 2, total: 2, percent: 100, difficulty: "Hard" },
        { topic: "Basic Algebra", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Exponents", correct: 2, total: 2, percent: 100, difficulty: "Hard" },
        { topic: "Graphing: Match Equation", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Graphing: Slope From Points", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Graphing: Y-Intercept", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Graphing: Word Problem Graph", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Linear vs Nonlinear Relationships", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Linear Equations and Inequalities", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Linear Functions and Graphing", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Function Notation", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Exponents and Radicals", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Pythagorean Theorem", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Graphing Parabolas", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "SAT Math Reasoning", correct: 1, total: 3, percent: 33, difficulty: "Easy" },
        { topic: "Data Interpretation", correct: 0, total: 2, percent: 0, difficulty: "Easy" },
        { topic: "Quadratic Formula", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Radical Expressions", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
        { topic: "Trigonometry Basics", correct: 0, total: 1, percent: 0, difficulty: "Easy" },
        { topic: "Algebra and Quadratic Word Problems", correct: 1, total: 1, percent: 100, difficulty: "Medium" },
      ],
    },
  },
];
